"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def fib(n, fib_keys={}):
    if n in fib_keys:
        return fib_keys[n]
    if n <= 2:
        return 1
    fib_keys[n] = fib(n - 1, fib_keys) + fib(n - 2, fib_keys)
    return fib_keys[n]


def solve(n):
    answer = 0
    count = 0
    x = 0
    while x < n:
        x = fib(count)
        if x % 2 == 0:
            answer += x
        count += 1
    return answer


print(solve(4000000))
