"""
The following problem is taken from Project Euler.

EVEN FIBONACCI NUMBERS

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Published on Friday, 19th October 2001, 06:00 pm; Solved by 770300;Difficulty rating: 5%
"""
