"""
The following problem is taken from Project Euler.

CYCLICAL FIGURATE NUMBERS

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

Published on Friday, 16th January 2004, 06:00 pm; Solved by 25281;Difficulty rating: 20%
"""


def problem_61():
	answer = None
	return answer


if __name__ == "__main__":
	print(problem_61())