"""
The following problem is taken from Project Euler.

HIGHLY DIVISIBLE TRIANGULAR NUMBER

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

Published on Friday, 8th March 2002, 06:00 pm; Solved by 222833;Difficulty rating: 5%
"""
