"""
Link: [https://projecteuler.net/problem=29]

The following problem is taken from Project Euler.

DISTINCT POWERS

Consider all integer combinations of ab for 2 â‰¤ a â‰¤ 5 and 2 â‰¤ b â‰¤ 5:
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
How many distinct terms are in the sequence generated by ab for 2 â‰¤ a â‰¤ 100 and 2 â‰¤ b â‰¤ 100?

Published on Friday, 25th October 2002, 06:00 pm; Solved by 106044;Difficulty rating: 5%
"""


def problem_29():
	answer = None
	return answer


if __name__ == "__main__":
	print(problem_29())