"""
The following problem is taken from Project Euler.

ZECKENDORF REPRESENTATION

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
Starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
Every positive integer can be uniquely written as a sum of nonconsecutive terms of the Fibonacci sequence. For example, 100 = 3 + 8 + 89.
Such a sum is called the Zeckendorf representation of the number.
For any integer n>0, let z(n) be the number of terms in the Zeckendorf representation of n.
Thus, z(5) = 1, z(14) = 2, z(100) = 3 etc.
Also, for 0<n<106, ∑ z(n) = 7894453.
Find ∑ z(n) for 0<n<1017.

Published on Friday, 18th June 2010, 05:00 pm; Solved by 2667;Difficulty rating: 35%
"""


def problem_297():
	answer = None
	return answer


if __name__ == "__main__":
	print(problem_297())