"""
The following problem is taken from Project Euler.

TRIANGULAR, PENTAGONAL, AND HEXAGONAL

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

Published on Friday, 6th June 2003, 06:00 pm; Solved by 71173;Difficulty rating: 5%
"""
