"""
Link: [https://projecteuler.net/problem=395]

The following problem is taken from Project Euler.

PYTHAGOREAN TREE


The Pythagorean tree is a fractal generated by the following procedure:


Start with a unit square. Then, calling one of the sides its base (in the animation, the bottom side is the base):


It can be shown that there exists at least one rectangle, whose sides are parallel to the largest square of the Pythagorean tree, which encloses the Pythagorean tree completely.


Find the smallest area possible for such a bounding rectangle, and give your answer rounded to 10 decimal places.


Published on Saturday, 22nd September 2012, 11:00 pm; Solved by 650;Difficulty rating: 40%
"""


def problem_395():
	answer = None
	return answer


if __name__ == "__main__":
	print(problem_395())