"""
Link: [https://projecteuler.net/problem=45]

The following problem is taken from Project Euler.

TRIANGULAR, PENTAGONAL, AND HEXAGONAL

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

Published on Friday, 6th June 2003, 06:00 pm; Solved by 71175;Difficulty rating: 5%
"""


def problem_45():
	answer = None
	return answer


if __name__ == "__main__":
	print(problem_45())