"""
Link: [https://projecteuler.net/problem=44]

The following problem is taken from Project Euler.

PENTAGON NUMBERS

Pentagonal numbers are generated by the formula, Pn=n(3nâˆ’1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 âˆ’ 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk âˆ’ Pj| is minimised; what is the value of D?

Published on Friday, 23rd May 2003, 06:00 pm; Solved by 58616;Difficulty rating: 5%
"""


def problem_44():
	answer = None
	return answer


if __name__ == "__main__":
	print(problem_44())